# Generated by Django 6.0.1 on 2026-01-26 09:20

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iam', '0002_user_organizations_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='organization_groups', to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(blank=True, related_name='groups', to='iam.organization')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted to members of this group for the associated organizations.', related_name='organization_groups', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
