# Generated by Django 6.0.1 on 2026-01-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='lease',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='housing.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='housing.tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='housing.property'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='housing.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='amenity',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
    ]
