# Generated by Django 6.0.1 on 2026-01-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
        migrations.AddField(
            model_name='lease',
            name='units',
            field=models.ManyToManyField(related_name='leases', to='housing.unit'),
        ),
    ]
