# Generated by Django 6.0.1 on 2026-01-27 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_remove_lease_unit_lease_units'),
        ('iam', '0003_remove_user_organization_organizationgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('APPLIANCE', 'Appliance'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('BROKEN', 'Broken')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='iam.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='housing.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(choices=[('MOVE_IN', 'Move In'), ('MOVE_OUT', 'Move Out'), ('ROUTINE', 'Routine'), ('COMPLAINT', 'Complaint Based')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('condition_rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('notes', models.TextField(blank=True)),
                ('condition_summary', models.JSONField(blank=True, default=dict)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='housing.lease')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='iam.organization')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='housing.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='inspections/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='housing.propertyinspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
