# Generated by Django 6.0.1 on 2026-01-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='housing.lease'),
        ),
    ]
