# Generated by Django 6.0.1 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(
                condition=~models.Q(transaction_id=''),
                fields=('provider', 'transaction_id'),
                name='uniq_payment_provider_transaction_id',
            ),
        ),
    ]
