/// MeroGhar Rental Management Application
///
/// Main entry point with notification badge support and localization.
/// Implements T215, T250 from tasks.md.
library;

import 'package:flutter/material.dart';
import 'package:flutter_app_badge/flutter_app_badge.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'providers/language_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize notification badge support
  await _initializeBadgeSupport();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => LanguageProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

/// Initialize notification badge support for the app.
Future<void> _initializeBadgeSupport() async {
  try {
    // Clear any existing badge on app start
    await FlutterAppBadge.count(0);
  } catch (e) {
    print('Error initializing badge support: $e');
  }
}

/// Update the app icon badge with unread notification count.
///
/// [count] - Number of unread notifications
Future<void> updateNotificationBadge(int count) async {
  try {
    await FlutterAppBadge.count(count);
  } catch (e) {
    print('Error updating notification badge: $e');
  }
}

/// Clear the app icon badge.
Future<void> clearNotificationBadge() async {
  try {
    await FlutterAppBadge.count(0);
  } catch (e) {
    print('Error clearing notification badge: $e');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) => Consumer<LanguageProvider>(
        builder: (context, languageProvider, child) => MaterialApp(
          title: 'MeroGhar',

          // Localization configuration
          locale: languageProvider.currentLocale,
          supportedLocales: LanguageProvider.supportedLocales,
          localizationsDelegates: const [
            // AppLocalizations.delegate, // Will be generated by flutter gen-l10n
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],

          // RTL support
          builder: (context, child) {
            // Force RTL for Arabic
            if (languageProvider.isRTL) {
              return Directionality(
                textDirection: TextDirection.rtl,
                child: child!,
              );
            }
            return child!;
          },

          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
            useMaterial3: true,
          ),

          home: const MyHomePage(title: 'MeroGhar - Rental Management'),
        ),
      );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _unreadNotifications = 0;

  void _incrementNotifications() {
    setState(() {
      _unreadNotifications++;
      // Update app icon badge
      updateNotificationBadge(_unreadNotifications);
    });
  }

  void _clearNotifications() {
    setState(() {
      _unreadNotifications = 0;
      // Clear app icon badge
      clearNotificationBadge();
    });
  }

  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
          actions: [
            // Notification badge indicator
            Stack(
              children: [
                IconButton(
                  icon: const Icon(Icons.notifications),
                  onPressed: _clearNotifications,
                ),
                if (_unreadNotifications > 0)
                  Positioned(
                    right: 8,
                    top: 8,
                    child: Container(
                      padding: const EdgeInsets.all(2),
                      decoration: BoxDecoration(
                        color: Colors.red,
                        borderRadius: BorderRadius.circular(10),
                      ),
                      constraints: const BoxConstraints(
                        minWidth: 18,
                        minHeight: 18,
                      ),
                      child: Text(
                        _unreadNotifications > 99
                            ? '99+'
                            : '$_unreadNotifications',
                        style: const TextStyle(
                          color: Colors.white,
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
              ],
            ),
          ],
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(
                Icons.notifications_active,
                size: 80,
                color: Colors.blue,
              ),
              const SizedBox(height: 24),
              const Text(
                'Notification Badge Demo',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 16),
              Text(
                'Unread Notifications: $_unreadNotifications',
                style: Theme.of(context).textTheme.headlineSmall,
              ),
              const SizedBox(height: 32),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton.icon(
                    onPressed: _incrementNotifications,
                    icon: const Icon(Icons.add),
                    label: const Text('Add Notification'),
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 24,
                        vertical: 16,
                      ),
                    ),
                  ),
                  const SizedBox(width: 16),
                  ElevatedButton.icon(
                    onPressed: _clearNotifications,
                    icon: const Icon(Icons.clear_all),
                    label: const Text('Clear All'),
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 24,
                        vertical: 16,
                      ),
                      backgroundColor: Colors.red,
                      foregroundColor: Colors.white,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 32),
              Container(
                padding: const EdgeInsets.all(16),
                margin: const EdgeInsets.symmetric(horizontal: 32),
                decoration: BoxDecoration(
                  color: Colors.blue.shade50,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Column(
                  children: [
                    Icon(Icons.info_outline, color: Colors.blue),
                    SizedBox(height: 8),
                    Text(
                      'The notification count is displayed both in-app and on the app icon badge.',
                      textAlign: TextAlign.center,
                      style: TextStyle(fontSize: 12),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      );

  @override
  void dispose() {
    // Clear badge when app is disposed
    clearNotificationBadge();
    super.dispose();
  }
}
